# Generated by Django 3.0.5 on 2020-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200410_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('Usd', 'Dollar'), ('Rub', 'Ruble'), ('Chips', 'Chips')], default='Rub', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('En', 'English'), ('Ru', 'Russian'), ('Pot', 'Potato')], default='Ru', max_length=10),
        ),
    ]
