# Generated by Django 3.0.5 on 2020-04-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('Pend', 'Pending'), ('Conf', 'Confirmed'), ('Cancld', 'Canceled')], max_length=10),
        ),
    ]
